import datetime

def generate_medical_report(prediction, confidence, patient_id="Unknown", patient_name="Unknown"):
    """
    Generates a formal medical report based on the AI model's prediction.
    """
    date_str = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    # Format confidence securely without exceeding 100%
    confidence_pct = round(confidence * 100, 2)
    
    if prediction.upper() == "PNEUMONIA":
        diagnosis = "Positive for Pneumonia"
        clinical_notes = (
            "The chest radiograph exhibits findings consistent with pneumonia. "
            "Regions of interest and potential opacities are highlighted in the accompanying "
            "Gradient-weighted Class Activation Mapping (Grad-CAM) visualization. "
            "Clinical correlation and immediate further medical evaluation are highly recommended."
        )
        recommendation = "Immediate consultation with a pulmonologist and further testing as per clinical guidelines."
    else:
        diagnosis = "Negative for Pneumonia (Normal)"
        clinical_notes = (
            "The chest radiograph appears relatively clear of typical pneumonic opacities "
            "based on the deep learning analysis. The accompanying Grad-CAM visualization "
            "reflects the normal resting features the model utilized for this inference."
        )
        recommendation = "Routine clinical follow-up as dictated by the patient's presentation."

    report = f"""
=========================================================
          AUTOMATED RADIOLOGY AI ANALYSIS REPORT         
=========================================================

Date of Report : {date_str}
Patient ID     : {patient_id}
Patient Name   : {patient_name}

---------------------------------------------------------
1. FINDINGS SUMMARY
---------------------------------------------------------
AI Diagnosis       : {diagnosis}
Model Confidence   : {confidence_pct}%

---------------------------------------------------------
2. CLINICAL NOTES
---------------------------------------------------------
{clinical_notes}

---------------------------------------------------------
3. RECOMMENDATIONS
---------------------------------------------------------
{recommendation}

=========================================================
DISCLAIMER: This diagnostic report was generated by an 
Artificial Intelligence model for informational/triage 
purposes only. It is NOT a replacement for a professional 
radiologist's independent diagnosis.
=========================================================
"""
    return report.strip()
